-Test 1: Teste 1 (-20.000)
Incorrect program result
 --- Input ---
> 6
>1
>2
>3
>4
>5
>6
>7
>6
>5
>4
>3
>2
>9
>8
>8
>8
>9
>1

 --- Program output ---
>n:a:a:a:a:a:a:b:b:b:b:b:b:c:c:c:c:c:c:N
>N
>Traceback (most recent call last):
>  File "funcoes1.py", line 46, in <module>
>    if consecutivo(a):
>NameError: name 'consecutivo' is not defined

 --- Expected output (text)---
> 'S'
>'N'
>'N'
>'N'
>'S'
>'N'
>'N'
>'N'
>'S'

-Summary of tests
>+------------------------------+
>|  1  test run/ 0 tests passed |
>+------------------------------+

