-Failed tests
Test 1: Test 1
Test 2: Test 2
-Test 1: Test 1 (-5.000)
Incorrect program result
 --- Input ---
> 1
>0
>-4

 --- Program output ---
>digite o valor de a:digite o valor de b:digite o valor de c:Traceback (most recent call last):
>  File "ex1.py", line 6, in <module>
>    d=b**2(-4*a*c)
>TypeError: 'int' object is not callable

 --- Expected output (text)---
> 'x1=2.00'
>'x2=-2.00'

-Test 2: Test 2 (-5.000)
Incorrect program result
 --- Input ---
> 1
>1
>1

 --- Program output ---
>digite o valor de a:digite o valor de b:digite o valor de c:Traceback (most recent call last):
>  File "ex1.py", line 6, in <module>
>    d=b**2(-4*a*c)
>TypeError: 'int' object is not callable

 --- Expected output (text)---
> 'SRR'

-Summary of tests
>+------------------------------+
>|  2 tests run/ 0 tests passed |
>+------------------------------+

