-Failed tests
Test 1: Teste 1
Test 4: Teste 4
-Test 1: Teste 1 (-10.000)
Incorrect program result
 --- Input ---
> 3
>1
>2
>1

 --- Program output ---
>Digite a quantidade de elementos da lista: digite um valor:digite um valor:digite um valor:Traceback (most recent call last):
>  File "pico.py", line 23, in <module>
>    if pico(lista):
>  File "pico.py", line 9, in pico
>    if a[i]<a[i-1]:
>NameError: name 'a' is not defined

 --- Expected output (text)---
> 'S'

-Test 4: Teste 4 (-10.000)
Incorrect program result
 --- Input ---
> 7
>2
>5
>10
>46
>25
>12
>7

 --- Program output ---
>Digite a quantidade de elementos da lista: digite um valor:digite um valor:digite um valor:digite um valor:digite um valor:digite um valor:digite um valor:Traceback (most recent call last):
>  File "pico.py", line 23, in <module>
>    if pico(lista):
>  File "pico.py", line 9, in pico
>    if a[i]<a[i-1]:
>NameError: name 'a' is not defined

 --- Expected output (text)---
> 'S'

-Summary of tests
>+------------------------------+
>|  4 tests run/ 2 tests passed |
>+------------------------------+

