-Failed tests
Test 1: Teste 1
Test 2: Teste 2
Test 3: Teste 3
-Test 1: Teste 1 (-6.667)
Incorrect program result
 --- Input ---
> 10

 --- Program output ---
>Quantidade de termos:Traceback (most recent call last):
>  File "serie1.py", line 8, in <module>
>    for i in range (1,i + 1):
>NameError: name 'i' is not defined

 --- Expected output (regular expression)---
>0.64563[0-9]*

-Test 2: Teste 2 (-6.667)
Incorrect program result
 --- Input ---
> 40

 --- Program output ---
>Quantidade de termos:Traceback (most recent call last):
>  File "serie1.py", line 8, in <module>
>    for i in range (1,i + 1):
>NameError: name 'i' is not defined

 --- Expected output (regular expression)---
>0.68080[0-9]*

-Test 3: Teste 3 (-6.667)
Incorrect program result
 --- Input ---
> 5

 --- Program output ---
>Quantidade de termos:Traceback (most recent call last):
>  File "serie1.py", line 8, in <module>
>    for i in range (1,i + 1):
>NameError: name 'i' is not defined

 --- Expected output (regular expression)---
>0.78333[0-9]*

-Summary of tests
>+------------------------------+
>|  3 tests run/ 0 tests passed |
>+------------------------------+

