s:1757:"<b>Failed tests</b><br />Test 1: Teste 1
<br />Test 2: Teste 2
<br />Test 3: Teste 3
<br /><b>Test 1: Teste 1 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 100
0.000001
</i></pre>
<br /> --- Program output ---
<br /><pre><i>Traceback (most recent call last):
  File "main.py", line 3, in &lt;module&gt;
    import funcoes
  File "/home/p13985/funcoes.py", line 20
    pi = pi + a
     ^
SyntaxError: invalid syntax
</i></pre>
<br /> --- Expected output (regular expression)---
<br /><pre><i>(.*3\.1415924[0-9]{8}
.*1\.6180328[0-9]{8})|(.*3\.1415924[0-9]{8}
.*1\.6180340[0-9]{8})
</i></pre>
<br /><b>Test 2: Teste 2 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 33
0.000000001
</i></pre>
<br /> --- Program output ---
<br /><pre><i>Traceback (most recent call last):
  File "main.py", line 3, in &lt;module&gt;
    import funcoes
  File "/home/p13985/funcoes.py", line 20
    pi = pi + a
     ^
SyntaxError: invalid syntax
</i></pre>
<br /> --- Expected output (regular expression)---
<br /><pre><i>.*3\.1415990[0-9]{8}
.*1\.6180324[0-9]{8}
</i></pre>
<br /><b>Test 3: Teste 3 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 1203
0.000000000001
</i></pre>
<br /> --- Program output ---
<br /><pre><i>Traceback (most recent call last):
  File "main.py", line 3, in &lt;module&gt;
    import funcoes
  File "/home/p13985/funcoes.py", line 20
    pi = pi + a
     ^
SyntaxError: invalid syntax
</i></pre>
<br /> --- Expected output (regular expression)---
<br /><pre><i>.*3\.1415926[0-9]{8}
.*1\.6180339[0-9]{8}
</i></pre>
<br /><b>Summary of tests</b><br /><pre><i>+------------------------------+
|  3 tests run/ 0 tests passed |
+------------------------------+
</i></pre>
<br /><br />";