s:1916:"<b>Failed tests</b><br />Test 1: Teste 1
<br />Test 2: Teste 2
<br />Test 3: Teste 3
<br /><b>Test 1: Teste 1 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 2
4
3
2
</i></pre>
<br /> --- Program output ---
<br /><pre><i>digite a quantidade de tomadas da extenção 1:digite a quantidade de tomadas da extenção 2:digite a quantidade de tomadas da extenção 3:digite a quantidade de tomadas da extenção 4:Traceback (most recent call last):
  File "tomadas.py", line 9, in &lt;module&gt;
    print('%'%TT)
ValueError: incomplete format
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i> '8'
</i></pre>
<br /><b>Test 2: Teste 2 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 6
6
6
6
</i></pre>
<br /> --- Program output ---
<br /><pre><i>digite a quantidade de tomadas da extenção 1:digite a quantidade de tomadas da extenção 2:digite a quantidade de tomadas da extenção 3:digite a quantidade de tomadas da extenção 4:Traceback (most recent call last):
  File "tomadas.py", line 9, in &lt;module&gt;
    print('%'%TT)
ValueError: incomplete format
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i> '21'
</i></pre>
<br /><b>Test 3: Teste 3 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 2
2
2
2
</i></pre>
<br /> --- Program output ---
<br /><pre><i>digite a quantidade de tomadas da extenção 1:digite a quantidade de tomadas da extenção 2:digite a quantidade de tomadas da extenção 3:digite a quantidade de tomadas da extenção 4:Traceback (most recent call last):
  File "tomadas.py", line 9, in &lt;module&gt;
    print('%'%TT)
ValueError: incomplete format
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i> '5'
</i></pre>
<br /><b>Summary of tests</b><br /><pre><i>+------------------------------+
|  3 tests run/ 0 tests passed |
+------------------------------+
</i></pre>
<br /><br />";