-Failed tests
Test 1: Teste 1
Test 2: Teste 2
Test 3: Teste 3
-Test 1: Teste 1 (-3.333)
Incorrect program result
 --- Input ---
> 7
>4
>0
>-1
>2
>2
>3
>8

 --- Program output ---
>digite o total de números:digite os elementos:digite os elementos:digite os elementos:digite os elementos:digite os elementos:digite os elementos:digite os elementos:Traceback (most recent call last):
>  File "listas.py", line 17, in <module>
>    print(maior(x))
>  File "listas.py", line 4, in maior
>    for i in range(lend(a)-1,0,-1):
>NameError: name 'lend' is not defined

 --- Expected output (text)---
> '5'

-Test 2: Teste 2 (-3.333)
Incorrect program result
 --- Input ---
> 5
>1
>2
>3
>4
>5

 --- Program output ---
>digite o total de números:digite os elementos:digite os elementos:digite os elementos:digite os elementos:digite os elementos:Traceback (most recent call last):
>  File "listas.py", line 17, in <module>
>    print(maior(x))
>  File "listas.py", line 4, in maior
>    for i in range(lend(a)-1,0,-1):
>NameError: name 'lend' is not defined

 --- Expected output (text)---
> '1'

-Test 3: Teste 3 (-3.333)
Incorrect program result
 --- Input ---
> 5
>-10
>-5
>2
>4
>9

 --- Program output ---
>digite o total de números:digite os elementos:digite os elementos:digite os elementos:digite os elementos:digite os elementos:Traceback (most recent call last):
>  File "listas.py", line 17, in <module>
>    print(maior(x))
>  File "listas.py", line 4, in maior
>    for i in range(lend(a)-1,0,-1):
>NameError: name 'lend' is not defined

 --- Expected output (text)---
> '7'
>

-Summary of tests
>+------------------------------+
>|  3 tests run/ 0 tests passed |
>+------------------------------+

