s:1943:"<b>Failed tests</b><br />Test 1: Teste 1
<br />Test 2: Teste 2
<br /><b>Test 1: Teste 1 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 10
4
1
2
3
4
5
6
7
8
9
10
5
9
18
20
</i></pre>
<br /> --- Program output ---
<br /><pre><i>Digite a Quantidade de Elementos de L1:Digite a Quantidade de Elementos de L2:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L2:Digite Elementos da L2:Digite Elementos da L2:Digite Elementos da L2:Traceback (most recent call last):
  File "contido.py", line 19, in &lt;module&gt;
    print (iguais(l1,l2))
  File "contido.py", line 5, in iguais
    for j in range(0,len(c),1):
NameError: name 'c' is not defined
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i> '2'
</i></pre>
<br /><b>Test 2: Teste 2 </b><br />Incorrect program result
<br /> --- Input ---
<br /><pre><i> 7
5
22
11
10
8
12
76
50
5
9
76
20
21
</i></pre>
<br /> --- Program output ---
<br /><pre><i>Digite a Quantidade de Elementos de L1:Digite a Quantidade de Elementos de L2:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L1:Digite Elementos da L2:Digite Elementos da L2:Digite Elementos da L2:Digite Elementos da L2:Digite Elementos da L2:Traceback (most recent call last):
  File "contido.py", line 19, in &lt;module&gt;
    print (iguais(l1,l2))
  File "contido.py", line 5, in iguais
    for j in range(0,len(c),1):
NameError: name 'c' is not defined
</i></pre>
<br /> --- Expected output (text)---
<br /><pre><i> '1'
</i></pre>
<br /><b>Summary of tests</b><br /><pre><i>+------------------------------+
|  2 tests run/ 0 tests passed |
+------------------------------+
</i></pre>
<br /><br />";